[package]
name = "vt_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "vt_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.27.0"
vt = { git = "https://github.com/asciinema/vt-rs", rev = "5d4e568" }
