name: Bug Report
description: Report a bug to help improve asciinema server
body:
  - type: markdown
    attributes:
      value: |
        **This is a bug tracker for asciinema server.**

        - If your issue is with the CLI recorder or the player, please open an issue in the related repository
        - If you're experiencing issues with asciinema.org, contact admin@asciinema.org
        - For feature requests, questions, or discussions, please use our [Forum](https://discourse.asciinema.org) or [GitHub Discussions](https://github.com/orgs/asciinema/discussions)

        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues and this bug has not been reported yet
          required: true
        - label: This is a bug report for asciinema server (not CLI or player)
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your operating system and version
      placeholder: e.g., macOS 14.1, Ubuntu 22.04, Fedora 39

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Browser name and version
      placeholder: e.g., Firefox 120, Safari 17, Chrome 119

  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: asciinema server version (only if self-hosting)
      placeholder: e.g., git tag v20250509 or git commit hash

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        This could include screenshots, browser extensions, network conditions, etc.
