#!/bin/bash

set -e

if sudo apt-get install -y autoconf libtool pkg-config; then
  if [ ! -e /usr/local/lib/libtsm.a ]; then
    echo "libtsm missing, compiling from source..."
    DIR=$(mktemp -d -t tsmXXXXXX)
    cd $DIR
    git clone https://github.com/asciinema/libtsm.git .
    git checkout asciinema
    test -f ./configure || NOCONFIGURE=1 ./autogen.sh
    ./configure --prefix=/usr/local
    make
    sudo make install
    sudo ldconfig
    cd -
  fi

  if [ -e /usr/local/lib/libtsm.a ]; then
      cd src && make && cd -
  fi
else
  echo "warning: sudo failed, not compiling libtsm and terminal binary"
fi

sudo apt-get install -y pngquant

if [ ! -e config/database.yml ]; then
  cp config/database.yml.example config/database.yml
fi

rm -f log/*
bundle install
bundle exec rake db:setup
mkdir -p tmp
touch tmp/restart.txt
