#!/bin/sh

set -e

if [ ! -e /usr/local/lib/libtsm.a ];
then
  echo "libtsm missing, compiling from source..."
  DIR=$(mktemp -d -t tsmXXXXXX)
  cd $DIR
  git clone git://github.com/sickill/libtsm.git .
  git checkout 7dfa43d
  test -f ./configure || NOCONFIGURE=1 ./autogen.sh
  ./configure --prefix=/usr/local
  make
  sudo make install
  sudo ldconfig
  cd -
fi

rm -f log/*
bundle install
bundle exec rake db:setup
mkdir -p tmp
touch tmp/restart.txt
