name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "v20*"

env:
  IMAGE_NAME: asciinema-server

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up outputs
        id: vars
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          IMAGE_TAG="${{ github.ref_name }}"
          # Strip "v" prefix from tag name
          [[ "${{ github.ref_type }}" == "tag" ]] && IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$IMAGE_TAG" == "main" ] && IMAGE_TAG=latest
          VERSION="${{ github.sha }}"
          [[ "${{ github.ref_type }}" == "tag" ]] && VERSION="${{ github.ref_name }}"
          [[ "${{ github.ref_type }}" == "branch" ]] && VERSION="${{ github.ref_name }}-${{ github.sha }}"
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_OUTPUT
          echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_OUTPUT
          echo VERSION=$VERSION >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.IMAGE_ID }}:${{ steps.vars.outputs.IMAGE_TAG }}
          labels: runnumber=${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.vars.outputs.VERSION }}
